# version: 2.0

# jobs:
#   build:
#     working_directory: ~/project
#     docker:
#       - image: circleci/node:14.17.5-stretch-browsers
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#   lint:
#     docker:
#       - image: circleci/node:14.17.5-stretch-browsers
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run lint
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - lint:
#           requires:
#             - build
