version: 2.0

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.16.2-stretch-browsers
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
